<center>![](https://i1.wp.com/www.jpzamora.com/wp-content/uploads/2017/02/bienvenidos.jpg?resize=768%2C350)


**Primeros pasos con datos brutos**

 - El mundo de las matrices con NumPy
 - Empoderando el análisis de datos con pandas
 - Limpieza de datos
 - Operaciones de datos


**Estadísticas inferenciales**

 - Varias formas de distribución
 - Un puntaje z
 - Un valor de p
 - Pruebas de una cola y dos colas
 - Un intervalo de confianza
 - Correlación
 - Z-test vs T-test
 - La prueba de chi-cuadrado de la independencia
 - ANOVA

**Encontrar una aguja en un pajar**

 - ¿Qué es la minería de datos?
 - Presentando un análisis
 - Estudiando el Titanic

**Sentido de los datos a travéz de la visualización avanzada**

 - Controlar las propiedades de línea de un gráfico
 - Creando múltiples parcelas
 - Parcelas de caja
 - Diagramas de dispersión con histogramas
 - Una matriz de diagrama de dispersión
 - Parcelas de área
 - Gráficos de burbujas

<center>![](https://www.packtpub.com/sites/default/files/9781784390150.png)

# Primero Pasos con Datos Crudos 

# ¿Qué es Python?

Python es un lenguaje de programación interpretado cuya filosofía hace hincapié en una sintaxis que favorezca un código legible.

Se trata de un lenguaje de programación multiparadigma, ya que soporta orientación a objetos, programación imperativa y, en menor medida, programación funcional. Es un lenguaje interpretado, usa tipado dinámico y es multiplataforma. <https://es.wikipedia.org/wiki/Python>

<center>![](https://pbs.twimg.com/media/C0j3X4fWgAAq6nW.jpg)

### R vs Python / R y Python: ¿Cuál es un buen enfoque?

Tanto R como Python son fuentes abiertas y son libres de usar lenguajes de programación de alto nivel. R está específicamente desarrollado para computación estadística. Tiene muchos paquetes / herramientas adicionales para apoyar el aprendizaje automático y el análisis de datos. Por otro lado, Python es un lenguaje de programación poderoso y de uso general con aplicaciones especiales en la preparación de datos , el borrado de datos y el análisis de datos.

## Primeros Pasos con Datos Crudos

En el mundo de la ciencia de datos, los datos crudos vienen en muchas
formas y tamaños. Hay una gran cantidad de información que se puede
extraer de estos datos sin procesar. Para dar un ejemplo, Amazon recopila
datos de la secuencia de clics que registra cada clic del usuario en el sitio
web. Esta información se puede utilizar para comprender si un usuario es
sensible al precio o si prefiere productos con mejor calificación
popular. Debes haber notado los productos recomendados en Amazon; se
derivan usando tales datos.

El primer paso para un análisis de este tipo sería analizar los datos
crudos. El análisis sintáctico de los datos implica los siguientes pasos:

- **Extraer datos de la fuente** : los datos pueden venir en muchas
formas, como Excel, CSV, JSON, bases de datos, etc. Python hace
que sea muy fácil leer datos de estas fuentes con la ayuda de algunos
paquetes útiles, que se tratarán en este capítulo.

- **Limpieza de los datos** : una vez que se ha realizado una
comprobación de cordura, es necesario limpiar los datos de forma
adecuada para que puedan utilizarse para el análisis. Puede tener un
conjunto de datos sobre los estudiantes de una clase y detalles sobre
su altura, peso y marcas. También puede haber ciertas filas con la
altura o el peso faltantes. Según el análisis que se realice, estas filas
con valores faltantes pueden ignorarse o reemplazarse con la altura o
el peso promedio.

**En este capítulo, cubriremos los siguientes temas:**

- Explorando matrices con NumPy

- Manejo de datos con pandas

- Leer y escribir datos de varios formatos


- Manejo de datos faltantes

- Manipulando datos

## El mundo de las matrices con NumPy

- Python, por Por defecto, viene con una estructura de datos, como List, que
se puede utilizar para operaciones de matriz, pero una lista de Python en sí
misma no es adecuada para realizar operaciones matemáticas pesadas, ya
que no está optimizada para ello.

- Una matriz NumPy requieren mucha menos memoria para almacenar la
misma cantidad de datos en comparación con una lista de Python, lo que
ayuda a leer y escribir desde la matriz de una manera más rápida.

### Creando una matriz

Una lista de números se puede pasar a la siguiente función de matriz para
crear un objeto de matriz NumPy:

In [3]:
import numpy as np

In [9]:
n_matriz = np.array([[0, 1, 2, 3],
                    [4, 5, 6, 7],
                    [8, 9, 10, 11]]
                   )

In [10]:
print(n_matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**ndim:** Esto da la cantidad de dimensiones de la matriz. A continuación,
se muestra que la matriz que definimos tenía dos dimensiones:

In [11]:
n_matriz.ndim

2

**n_matriz** tiene un rango de 2, que es una matriz 2D.

**shape**: Esto le da el tamaño de cada dimensión de la matriz:

In [12]:
n_matriz.shape

(3, 4)

**size**: Esto da la cantidad de elementos:

In [38]:
n_matriz.size

12

El número total de elementos en n_matriz 12.

**dtype**: Esto le da el tipo de datos de los elementos en la matriz:

In [13]:
n_matriz.dtype

dtype('int32')

los número se almacena como int32en n_matriz.

## Operaciones matemáticas

Cuando tienes una variedad de datos, le gustaría realizar ciertas
operaciones matemáticas en él. Ahora vamos a discutir algunos de los más
importantes en las siguientes secciones.

### SUBSTRACCIÓN DE MATRIZ

Los siguientes comandos restan la matriz a menos la matriz b para optener una matriz c. La resta sucede elemento a elemento

In [14]:
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

### Cuadrando una matriz

El siguiente comando aumenta cada elemento a la potencia de 2 para
obtener este resultado:

In [15]:
b ** 2

array([ 1,  4,  9, 16], dtype=int32)

### UNA FUNCIÓN TRIGONOMÉTRICA REALIZADA EN LA MATRIZ

El seguiente comando aplica coseno a cada uno de los valores en
la matriz b para obtener el siguiente resultado:

In [16]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### OPERACIONES CONDICIONALES

El seguiente comando aplicará una operación condicional a cada de los
elementos de la matriz b, para generar los valores booleanos respectivos:

In [17]:
b < 2

array([ True, False, False, False])

### MULTIPLICACIÓN DE MATRIZ

Dos matrices se puede multiplicar elemento por elemento o en un
punto producto. Los siguientes comandos realizarán la multiplicación
elemento a elemento:

In [20]:
A1 = np.array([[1 ,1],
             [0, 1]])

In [21]:
A2 = np.array([[2, 0],
              [3, 4]])

In [22]:
A1 * A2

array([[2, 0],
       [0, 4]])

In [23]:
np.dot(A1, A2)

array([[5, 4],
       [3, 4]])

### Indexación y rebanado

Si quieres seleccionar un elemento particular de una matriz, se puede lograr
usando índices:

In [24]:
n_matriz[0, 1]

1

El comando anterior se seleccione la primera matriz y luego seleccione el
segundo valor en la matriz. También se puede ver como una intersección de
la primera fila y la segunda columna de la matriz.
Si se debe seleccionar un rango de valores en una fila, entonces podemos
usar el siguiente comando:

In [25]:
n_matriz[0, 0:3]

array([0, 1, 2])

El valor 0:3 selecciona los primeros tres valores de la primera fila.

La fila completa de valores se puede seleccionar con el siguiente comando:

In [27]:
n_matriz[0,:]

array([0, 1, 2, 3])

Usando lo siguiente comando, una columna completa de valores debe
ser seleccionado:

In [29]:
n_matriz[:,1]

array([1, 5, 9])

### Manipulación de formas

Una vez que la matriz se ha creado, también podemos cambiar su forma. El
siguiente comando aplana la matriz:

In [31]:
n_matriz.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

El siguiente comando cambia la forma de la matriz a un formato de seis filas
y dos columnas. Además, tenga en cuenta que al remodelar, la nueva forma
debe tener la misma cantidad de elementos que la anterior:

In [35]:
n_matriz.shape = (6, 2)
n_matriz

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
n_matriz.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

![](http://www.grandespymes.com.ar/wp-content/uploads/2015/11/gracias-2323.jpg)